/**
 * Notebook Export Routes — server-side PDF (Playwright) & DOCX generation.
 *
 * POST /api/notebooks/:id/export/pdf   — render HTML → PDF via headless Chromium
 * POST /api/notebooks/:id/export/docx  — convert HTML → native .docx
 *
 * Both endpoints expect { content: "<html>", title: "..." } in the request body.
 * Images should already be embedded as base64 data URIs by the client.
 */

const express = require('express');
const router = express.Router();
const { buildExportHTML, cleanContentForExport } = require('../templates/exportTemplate');

function requireAuth(req, res, next) {
    if (req.session?.user) return next();
    res.status(401).json({ error: 'Unauthorized' });
}

// ── PDF Export (Playwright) ─────────────────────────────────────────────────

router.post('/:id/export/pdf', requireAuth, async (req, res) => {
    const { content, title = 'Notebook' } = req.body;
    if (!content) return res.status(400).json({ error: 'No content provided' });

    const author = req.session.user.name || req.session.user.email || '';

    let playwright;
    try {
        playwright = require('playwright');
    } catch (e) {
        console.error('[Export] Playwright not available, falling back to basic PDF');
        return res.status(500).json({ error: 'PDF export requires Playwright. Install with: npm install playwright && npx playwright install chromium' });
    }

    let browser = null;
    try {
        console.log(`[Export] Starting PDF export for notebook ${req.params.id}: "${title}"`);
        const startTime = Date.now();

        // Clean and wrap content in professional template
        const cleanedContent = cleanContentForExport(content);
        const exportHTML = buildExportHTML(cleanedContent, { title, author });

        // Launch headless browser
        browser = await playwright.chromium.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
        });

        const context = await browser.newContext();
        const page = await context.newPage();

        // Set content (base64 images are already embedded)
        await page.setContent(exportHTML, { waitUntil: 'networkidle' });

        // Wait for Google Fonts to load (needed for custom font-family support)
        await page.waitForTimeout(1500);

        // Generate PDF with proper settings
        const pdfBuffer = await page.pdf({
            format: 'Letter',
            margin: {
                top: '0.75in',
                right: '0.85in',
                bottom: '0.9in',
                left: '0.85in'
            },
            printBackground: true,
            displayHeaderFooter: true,
            headerTemplate: `
                <div style="font-size: 8px; color: #999; width: 100%; padding: 0 0.85in; display: flex; justify-content: space-between;">
                    <span>${title.replace(/"/g, '&quot;').replace(/</g, '&lt;')}</span>
                    <span></span>
                </div>
            `,
            footerTemplate: `
                <div style="font-size: 8px; color: #bbb; width: 100%; padding: 0 0.85in; display: flex; justify-content: space-between;">
                    <span>Generated by BeeFlow</span>
                    <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
                </div>
            `,
        });

        const duration = Date.now() - startTime;
        console.log(`[Export] PDF generated: ${(pdfBuffer.length / 1024).toFixed(1)} KB in ${duration}ms`);

        // Send PDF response
        const safeFilename = title.replace(/[^a-zA-Z0-9.\-_ ]/g, '_').trim() || 'notebook';
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="${safeFilename}.pdf"`);
        res.setHeader('Content-Length', pdfBuffer.length);
        res.send(pdfBuffer);

    } catch (err) {
        console.error('[Export] PDF generation failed:', err);
        res.status(500).json({ error: 'PDF generation failed: ' + err.message });
    } finally {
        if (browser) {
            try { await browser.close(); } catch (e) { }
        }
    }
});

// ── DOCX Export (html-to-docx) ──────────────────────────────────────────────

router.post('/:id/export/docx', requireAuth, async (req, res) => {
    const { content, title = 'Notebook' } = req.body;
    if (!content) return res.status(400).json({ error: 'No content provided' });

    try {
        console.log(`[Export] Starting DOCX export for notebook ${req.params.id}: "${title}"`);
        const startTime = Date.now();

        let HTMLtoDOCX;
        try {
            HTMLtoDOCX = require('html-to-docx');
            // Handle both default and named exports
            if (HTMLtoDOCX.default) HTMLtoDOCX = HTMLtoDOCX.default;
        } catch (e) {
            return res.status(500).json({ error: 'html-to-docx not installed. Run: npm install html-to-docx' });
        }

        // Clean content for Word export
        const cleanedContent = cleanContentForExport(content);

        // Debug: log font-family spans in input vs cleaned
        const inputFontMatches = (content.match(/font-family/gi) || []).length;
        const cleanedFontMatches = (cleanedContent.match(/font-family/gi) || []).length;
        console.log(`[Export] DOCX font-family spans: input=${inputFontMatches}, afterClean=${cleanedFontMatches}`);
        if (inputFontMatches > 0) {
            // Log a sample span for debugging
            const sampleMatch = content.match(/<span[^>]*style="[^"]*font-family[^"]*"[^>]*>[^<]{0,50}/i);
            console.log(`[Export] Sample font span:`, sampleMatch?.[0] || 'none found');
        }

        // Wrap in a minimal HTML structure that html-to-docx expects
        const htmlForDocx = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${title}</title>
<style>
    body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; line-height: 1.5; color: #1a1a1a; }
    h1 { font-size: 20pt; font-weight: bold; color: #111; margin-top: 18pt; margin-bottom: 8pt; border-bottom: 1pt solid #d0d0d0; padding-bottom: 4pt; }
    h2 { font-size: 16pt; font-weight: bold; color: #1e293b; margin-top: 14pt; margin-bottom: 6pt; }
    h3 { font-size: 13pt; font-weight: bold; color: #334155; margin-top: 12pt; margin-bottom: 4pt; }
    p { margin-bottom: 6pt; }
    table { width: 100%; border-collapse: collapse; margin: 8pt 0; }
    th, td { border: 1pt solid #999; padding: 4pt 8pt; vertical-align: top; text-align: left; }
    th { background-color: #f0f0f0; font-weight: bold; }
    blockquote { border-left: 3pt solid #3b82f6; padding: 6pt 12pt; margin: 8pt 0; background: #f8f9fa; }
    code { font-family: Consolas, monospace; font-size: 9pt; background: #f1f5f9; padding: 1pt 3pt; }
    pre { background: #f5f5f5; padding: 10pt; font-family: Consolas, monospace; font-size: 9pt; margin: 8pt 0; border: 1pt solid #ddd; }
    pre code { background: none; padding: 0; }
    ul, ol { margin-left: 0.4in; margin-bottom: 6pt; }
    li { margin-bottom: 2pt; }
    img { max-width: 100%; }
</style>
</head>
<body>
    ${cleanedContent}
</body>
</html>`;

        const docxBuffer = await HTMLtoDOCX(htmlForDocx, null, {
            table: { row: { cantSplit: true } },
            footer: true,
            pageNumber: true,
            title: title,
            margin: {
                top: 1440,    // 1 inch in twips (1 inch = 1440 twips)
                right: 1440,
                bottom: 1440,
                left: 1440,
            },
            font: 'Calibri',
            fontSize: 22,  // half-points (22 = 11pt)
        });

        const duration = Date.now() - startTime;
        const buffer = Buffer.from(docxBuffer);
        console.log(`[Export] DOCX generated: ${(buffer.length / 1024).toFixed(1)} KB in ${duration}ms`);

        const safeFilename = title.replace(/[^a-zA-Z0-9.\-_ ]/g, '_').trim() || 'notebook';
        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
        res.setHeader('Content-Disposition', `attachment; filename="${safeFilename}.docx"`);
        res.setHeader('Content-Length', buffer.length);
        res.send(buffer);

    } catch (err) {
        console.error('[Export] DOCX generation failed:', err);
        res.status(500).json({ error: 'DOCX generation failed: ' + err.message });
    }
});

module.exports = router;
